### ISSUE TITLE
[FEATURE REQUEST] Adding favicon to the title bar

### ISSUE THREAD

**Issue by keerthana054** [EddieHubCommunity/support#4920] opened 2022-08-09 13:27 UTC
### Description of feature request, idea

Adding logo of eddiehub to the title bar would be more engaging to the viewers. So, I got this idea of adding it. And this is my first issue raising in eddiehub organization. Looking forward to work :)

### Add (multiple) screenshot links (if applicable)

![image](https://user-images.githubusercontent.com/91015385/183658900-931dc3af-fabf-4395-bd38-7a00f9e0fbd8.png)

**Comment by prakhartiwari2507** [comment] 2022-08-16 04:32
Hey, I can work on it! May I make a PR?

**Comment by keerthana054** [comment] 2022-08-16 05:54
> Hey, I can work on it! May I make a PR?

Hello, I've completed the task, and my PR is ready to be merged.

**Comment by ayushdotdev** [comment] 2022-09-26 10:31
the issue is officially not closed did your PR got merged ? @keerthana054

**Comment by keerthana054** [comment] 2022-09-26 10:34
> the issue is officially not closed did your PR got merged ? @keerthana054

Not yet!

**Comment by RaheemAmer** [comment] 2022-10-01 01:15
Are there any updates on this issue or PR made by you @keerthana054 ?

**Comment by keerthana054** [comment] 2022-10-01 09:03
> Are there any updates on this issue or PR made by you @keerthana054 ?

This issue has another clone #4930 , where I've updated my code long ago. But not got merged yet. Does this PR come under hactoberfest?!

**Comment by RaheemAmer** [comment] 2022-10-01 09:09
I don't know honestly. maybe @schmelto can help to answer this question

**Comment by keerthana054** [comment] 2022-10-01 09:11
> I don't know honestly. maybe @schmelto can help to answer this question

yeah! okay.. or else I'm ready to create new issue and pr on it.

**Comment by Ayushbajpai19** [comment] 2022-10-06 16:14
Can i get to contribute in this repo please?

**Closed** 2022-10-07 06:18 UTC
Labels: enhancement, good first issue, 🏁 status: ready for dev, 🔢 points: 1, 🟩 priority: low, 💻 aspect: code
